//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AlgLab2DCodeCheck.rc
//
#define IDOK                            1
#define IDC_NODROP                      106
#define IDC_PIC                         1000
#define IDC_COMBO1                      1001
#define IDC_COMBO_REGIONTYPE            1001
#define IDC_COMBO_CODETYPE              1001
#define IDC_COMBO_DIRECT                1001
#define IDC_EDIT1                       1002
#define IDC_COMBO_REGIONID              1002
#define IDC_EDIT_WORD                   1002
#define IDC_EDIT_DEVIATION              1002
#define IDC_EDIT_TOP                    1002
#define IDC_EDIT_HORSCAL                1002
#define IDC_EDIT_SPSOUS                 1002
#define IDC_EDIT_AREA                   1002
#define IDC_BUTTON_SETTYPE              1003
#define IDC_EDIT_VERSCAL                1003
#define IDC_EDIT_AREA2                  1003
#define IDC_COMBO_PRODUCT_TYPE          1004
#define IDC_COMBO_CODETYPE2             1004
#define IDC_COMBO_POLAR                 1004
#define IDB_BITMAP4                     1006
#define IDC_BUTTON_PARA_SET             1006
#define IDC_BUTTON_SAVE                 1007
#define IDD_DIALOG_PROP                 1007
#define IDC_STATIC_CHECKRESULT          1008
#define IDD_DIALOG_PRAR                 1009
#define IDC_BUTTON_MODIFY_MODE          1010
#define IDC_BUTTON_RECORD               1011
#define IDC_EDIT_EXPCODE                1012
#define IDC_EDIT_RESULT_CODE            1013
#define IDC_BUTTON_SETTIGHT             1014
#define IDC_BUTTON_CHAR                 1014
#define IDC_BUTTON_TEST                 1015
#define IDD_DINGWEI_QR                  1015
#define IDC_BUTTON_TYPE_SET             1016
#define IDD_DIALOG_PARASETUP            1016
#define IDC_BUTTON_ONLYREAD             1017
#define IDD_IN_HOEVER                   1018
#define IDD_IN_REGION                   1019
#define IDD_OUTRANGE                    1020
#define IDD_DIALOG_DENGJI               1021
#define IDD_DIALOG_PDF417ISO            1022
#define IDD_DIALOG_DENGJI2              1023
#define IDD_DIALOG_AIMDRM2006           1023
#define IDD_ZOUBAN                      1024
#define IDD_DIALOG1                     1025
#define IDD_DIALOG_CORR                 1025
#define IDD_TIMEOUT                     1026
#define IDB_BITMAP_BACK                 1026
#define IDB_BITMAP_TABBACK              1028
#define IDB_BITMAP_GRADEBACK            1029
#define IDC_BUTTON1                     1034
#define IDC_BUTTON_LOOOK_CHAR           1034
#define IDC_BTN_ADVANCEPARA             1034
#define IDC_COMBO_CHANNEL               1035
#define IDC_COMBO_CODETYPE1             1036
#define IDC_EDIT2                       1037
#define IDC_STATIC_CHAN                 1038
#define IDC_EDIT_LEFT1                  1038
#define IDC_EDIT_ZOUBANDISDOWN          1038
#define IDC_CHECK_ALL                   1039
#define IDC_EDIT_BOTTOM1                1039
#define IDC_EDIT_ZOUBANDISLEFT          1039
#define IDC_BUTTON_SAVEALL              1040
#define IDC_EDIT_RIGHT1                 1040
#define IDC_EDIT_ZOUBANDISRIGHT         1040
#define IDC_EDIT6                       1041
#define IDC_EDIT_ALLAREA1               1041
#define IDC_EDIT_ZOUBANSTDDOWN          1041
#define IDC_CHECK_QRLOC                 1042
#define IDC_CHECK_HORVER                1042
#define IDC_CHECK_INRGION               1042
#define IDC_CHECK_OUTRANGE              1042
#define IDC_CHECK_INREGION              1042
#define IDC_EDIT_ZOUBANSTDLEFT          1042
#define IDC_EDIT_MAXGRAY                1043
#define IDC_EDIT_SINGLE1                1043
#define IDC_EDIT_ZOUBANSTDRIGHT         1043
#define IDC_EDIT_LEFT                   1044
#define IDC_CHECK_HORVER2               1044
#define IDC_EDIT_ZOUBANTHRESH           1044
#define IDC_RADIO_AUTO                  1045
#define IDC_EDITRIGHT                   1045
#define IDC_RADIO_NORM                  1046
#define IDC_EDIT_SINGLEAREA             1046
#define IDC_RADIO_SETRATE               1047
#define IDC_EDIT_ALLAREA                1047
#define IDC_EDIT_BOTTOM                 1048
#define IDC_CHECK_GAO                   1049
#define IDC_EDIT_SHOWRATE_X             1051
#define IDC_EDIT_TOP1                   1051
#define IDC_EDIT_SHOWRATE_Y             1052
#define IDC_SCROLLBAR_HOR               1053
#define IDC_SCROLLBAR_VER               1054
#define IDC_CHECK_DENGJI                1055
#define IDC_BUTTON_READDEFAULT          1056
#define IDC_COMBO_DENGJI                1056
#define IDC_BUTTON_WRITEDEFAULT         1057
#define IDC_STATIC_DENGJI               1057
#define IDC_STATIC_CHECKGRADE1          1057
#define IDC_BUTTON_SETDENG              1058
#define IDC_COMBO_DENGJI2               1058
#define IDC_STATIC_BIAOZHUN             1059
#define IDC_STATIC_DENGJI2              1059
#define IDC_STATIC_CHECKGRADE           1059
#define IDC_COMBO_GBTYPE                1060
#define IDC_BUTTON_SETDENG2             1060
#define IDC_STATIC_BIAOZHUN2            1061
#define IDC_CHECK_ZOUBAN                1061
#define IDC_STATIC_CHECKSTD             1061
#define IDC_COMBO_GBTYPE2               1062
#define IDC_CHECK_INLOC                 1062
#define IDC_BUTTON_SETZOUBAN            1063
#define IDC_CHECK_ZOUBANUP              1063
#define IDC_STATIC_SPSOUS               1064
#define IDC_BUTTON_SETINLOC             1064
#define IDC_BUTTON_SETZOUBAN2           1064
#define IDC_STATIC_CZSOUS               1065
#define IDC_EDIT_CZSOUS                 1066
#define IDC_SHOWDLG1                    1067
#define IDC_CHECK_ZOUBANDOWN            1067
#define IDC_CHECK_RESULTMODE            1068
#define IDC_CHECK_ZOUBANLEFT            1068
#define IDC_CHECK_ALIGNCORRECT          1069
#define IDC_CHECK_ZOUBANRIGHT           1069
#define IDC_EDIT_CORRPIXEL              1070
#define IDC_CHECK_ISWHITEZOUBAN         1070
#define IDC_STATIC_1                    1071
#define IDC_CHECK_CODE                  1072
#define IDC_EDIT_CODEL                  1073
#define IDC_EDIT_CODEH                  1074
#define IDC_STATIC18                    1075
#define IDC_CHECK_IsTurnedResult        1076
#define IDC_CHECK_TIMEOUT               1077
#define IDC_STATIC_CHECKRANGE           1077
#define IDC_STATIC_SINGLETIME           1078
#define IDC_STATIC_ALLTIME              1079
#define IDC_EDIT_ALLTIME                1080
#define IDC_EDIT_SINGLETIME             1081
#define IDC_STATIC_SHOWMODE             1082
#define IDC_STATIC_2DTYPE               1085
#define IDC_STATIC_POLAR                1086
#define IDC_BTN_EXIT                    1087
#define IDC_STATIC_MAXPIXEL             1088
#define IDC_STATIC_HOR                  1089
#define IDC_STATIC_VER                  1090
#define IDC_STATIC_EXPCODE              1091
#define IDC_STATIC_RECCODE              1092
#define IDC_STATIC_RECRANGE             1093
#define IDC_STATIC_DEVIATION            1094
#define IDC_STATIC_MAXGRAY              1095
#define IDC_STATIC_ADDTAB               1102
#define IDC_STATIC_TOP                  1103
#define IDC_STATIC_LEFT                 1104
#define IDC_STATIC_BOTTOM               1105
#define IDC_STATIC_RIGHT                1106
#define IDC_STATIC_SINGLEAREA           1107
#define IDC_STATIC_ALLAREA              1108
#define IDC_STATIC_TO                   1109
#define IDC_SHOWTAB                     1110
#define IDC_STATIC_TITLE                1111
#define IDC_TAB_SETUP                   1114
#define IDC_SPIN_CODEL                  1118
#define IDC_SPIN_CODEH                  1119
#define IDC_SPIN_HOR                    1120
#define IDC_SPIN_VER                    1121
#define IDC_SPIN_MAXGRAY                1122
#define IDC_SPIN_DEV                    1123
#define IDC_SPIN_MAXPIXEL               1123
#define IDC_SPIN_TOP                    1125
#define IDC_SPIN_LEFT                   1126
#define IDC_SPIN_SINGLETIME             1126
#define IDC_SPIN_BOTTOM                 1127
#define IDC_SPIN_ALLTIME                1127
#define IDC_SPIN_SPSOUS                 1127
#define IDC_SPIN_RIGHT                  1128
#define IDC_SPIN_CZSOUS                 1128
#define IDC_DRAW_LOC                    1128
#define IDC_SPIN_ALLAREA                1129
#define IDC_DRAW_OFFSET                 1129
#define IDC_SPIN_SPSRANGE               1129
#define IDC_SPIN_SINGLEAREA             1130
#define IDC_SLIDER_DEV                  1130
#define IDC_SLIDER_MAXGRAY              1131
#define IDC_SLIDER_SPSOUS               1131
#define IDC_SLIDER_CZSOUS               1132
#define IDC_SLIDER_BOTTOM               1133
#define IDC_SLIDER_VERDIS               1133
#define IDC_SLIDER_RIGHT                1134
#define IDC_SLIDER_HORDIS               1134
#define IDC_SLIDER_SINGLEAREA           1135
#define IDC_SLIDER_ZBRANGE              1135
#define IDC_SLIDER_ALLAREA              1136
#define IDC_SLIDER_TOP                  1137
#define IDC_SLIDER_LEFT                 1138
#define IDC_SLIDER_SINGLETIME           1139
#define IDC_SLIDER_ALLTIME              1140
#define IDC_EDIT_CHECKRESULT            1141
#define IDC_STATIC_STD                  1143
#define IDC_STATIC_STDVALUE             1144
#define IDC_BUTTON_ADVPARA              1145
#define IDC_STATIC_                     1146
#define IDC_STATIC_SHOWIMAGE            1146
#define IDC_STATIC_DIRECT               1148
#define IDC_STATIC_AREA                 1149
#define IDC_SPIN_AREA                   1150
#define IDC_STATIC_CONTRAST             1151
#define IDC_EDIT_CONTRAST               1152
#define IDC_SPIN_CONTRAST               1153
#define IDC_SLIDER_AREA                 1154
#define IDC_SLIDER_CONTRAST             1155
#define IDC_STATIC_SHOW                 1156
#define IDC_STATIC_EXP                  1157
#define IDC_SPIN_CONTRAST2              1157
#define IDC_SPIN_PERCENT                1157
#define IDC_EDIT_ZOUBANDISUP            1158
#define IDC_SLIDER_PERCENT              1158
#define IDC_EDIT_ZOUBANSTDUP            1159
#define IDC_STATIC_DOWN                 1160
#define IDC_EDIT_ZOUBANSTDVER           1160
#define IDC_STATIC_UP                   1161
#define IDC_STATIC_VERDIS               1161
#define IDC_STATIC_UPRANGE              1162
#define IDC_STATIC_RANGE                1162
#define IDC_STATIC_DOWNRANGE            1163
#define IDC_EDIT_ZOUBANSTDHOR           1163
#define IDC_STATIC_LEFTRANGE            1164
#define IDC_STATIC_RIGHTRANGE           1165
#define IDC_EDIT_ZOUBANRANGE            1165
#define IDC_SLIDER_THRESH               1166
#define IDC_RADIO3                      1169
#define IDC_RADIO_LEFT                  1170
#define IDC_RADIO_RIGHT                 1171
#define IDC_RADIO_UP                    1172
#define IDC_STATIC_HORDIS               1173
#define IDC_RADIO_DOWN                  1175
#define IDC_SPIN_ZBVER                  1176
#define IDC_SPIN_ZBVER2                 1177
#define IDC_SPIN_ZBHOR                  1177
#define IDC_STATIC_PERCENT              1177
#define IDC_EDIT_PERCENT                1178
#define IDC_CHECK_IMAGESMOTH            1179
#define IDC_CHECK_IMAGESMOOTH           1180
#define IDC_CHECK_IMAGESMOOTH2          1181
#define IDC_CHECK_IMAGEZOOM             1181
#define IDC_EDIT_SFRADIO                1182
#define IDC_EDIT3                       1183
#define IDC_STATICSFBL                  1184
#define IDC_EDIT_RESULTNUM              1185
#define IDC_STATIC_RESULTNUM            1186
#define IDC_STATIC_RESULT               1187
#define IDC_STATIC_PROPPARAM            1188
#define IDC__READWRITEDEFAULTPARA       1189
#define IDC_STATIC_ADVANCEPROPPARAM     1190
#define IDC_STATIC_CHECKPARAM           1191
#define IDC_STATIC_2DBARCODEGRADE       1192
#define IDC_STATIC_ADVANCEPARAPARAM     1193
#define IDC_STATIC_CHECK_CODELOSE       1194
#define IDC_STATIC_YARDSDIRTY           1195
#define IDC_STATIC_TIMEOUT              1196
#define IDC_STATIC_ZOUBAN               1197
#define IDCANCEL1                       1199
#define IDC_EDIT_MORELINKQIAN2          2038
#define IDC_CHECK5                      3023
#define IDC_CHECK2                      3063
#define IDC_CHECK6                      3064
#define IDC_CHECK1                      3065
#define IDC_CHECK3                      3066
#define IDC_CHECK4                      3067
#define IDC_CHECK7                      3068
#define IDC_CHECK_NOALL                 3071
#define IDC_STATIC_QRDW                 3072

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1030
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           1031
#endif
#endif
